create database bootcamp_2409p;

use bootcamp_2409p;

--You can write comment here
--CASE INCENTIVE
-- NAME CONVENTION, which differ to Java (i.e. FIRST_NAME)
CREATE TABLE CUSTOMERS(
ID INTEGER,
FIRST_NAME VARCHAR(100),
LAST_NAME VARCHAR(50),
DOB DATE,
COUNTRY VARCHAR(2)


);

SELECT * FROM CUSTOMERS;
DELETE FROM CUSTOMERS;

INSERT INTO CUSTOMERS (ID, FIRsT_NAME, LAST_NAME, DOB, COUNTRY) 
VALUES (1, 'VINCENT', 'LAU', '1900-12-01','HK');
INSERT INTO CUSTOMERS (ID, FIRST_NAME, LAST_NAME, DOB, COUNTRY) 
VALUES (2, 'SALLY', 'WONG', '1910-06-30','HK');
INSERT INTO CUSTOMERS (ID, FIRST_NAME, LAST_NAME, DOB, COUNTRY) 
VALUES (3, 'JEFFERY', 'LAU', '1910-12-31','US');

-- '*' means all columns as result.alter
-- Where is a conditional clause for filtering rows
-- SELECT is for filtering columns fro result set
-- "BETWEEN AND" is inclusive
SELECT * FROM CUTOMERS WHERE LAST_NAME = 'LAU';
SELECT FIRST_NAME, COUNTRY FROM CUSTOMERS WHERE COUNTRY = 'HK';
SELECT * FROM CUSTOMERS WHERE DOB BETWEEN '1910-01-01' AND '1910-12-31';
SELECT * FROM CUSTOMERS WHERE DOB = '1910-06-30';
SELECT * FROM CUSTOMERS WHERE LAST_NAME  = 'LAU' AND COUNTRY = 'HK';
SELECT * FROM CUSTOMERS WHERE LAST_NAME  = 'LAU' OR COUNTRY = 'HK';
SELECT * FROM CUSTOMERS WHERE (LAST_NAME  = 'LAU' OR COUNTRY = 'HK') AND DOB >= '1910-01-01';

-- DECIMAL (5,2) -> 2 stands from decimal places
CREATE TABLE ORDERS(
ID INTEGER,
AMOUNT DECIMAL (5,2),
ORDER_DATE DATE,
CUSTOMER_ID INTEGER
);

-- For insert, we can skip the column name, but you have assign all columns value at once.
INSERT INTO ORDERS VALUES (1, 100.52, '1940-10-20', 2);
INSERT INTO ORDERS VALUES (2, 999.99, '1939-12-31', 1); 
INSERT INTO ORDERS VALUES (3, 0.99, '1940-10-20', 3);
INSERT INTO ORDERS (ID, ORDER_DATE, CUSTOMER_ID) VALUES (4, '1940-10-21', 1);
-- INSERT INTO ORDERS VALUES (1,1200.99, '1939-12-31', 1); -- OUT OF RANGE VALUE FOR 'AMOUNT'

UPDATE ORDERS SET AMOUNT = 999.99 WHERE ID =4;


SELECT * FROM ORDERS WHERE AMOUNT > 100.99;


